stages:
    - build
    - package

variables:
    GIT_STRATEGY: clone
    PYTHON_IMAGE: "code.ornl.gov:4567/rse/datastreams/ssm/clients/ssm-rest-python-client/python:3.6"

include:
     remote: "https://code.ornl.gov/rse-deployment/rse-sharables/-/raw/master/.gitlab-ci-before_script.yml"

lint:
    stage: build
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f .ci/Dockerfile -t ssm-rest-python-client-lint .
        - docker run ssm-rest-python-client-lint pipenv run make lint
        - func_rse_docker_cleanup
    tags:
        - rse-multi-builder

lint-complexity:
    stage: build
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f .ci/Dockerfile -t ssm-rest-python-client-lint .
        - docker run ssm-rest-python-client-lint pipenv run make lint-complexity
        - func_rse_docker_cleanup
    tags:
        - rse-multi-builder
    allow_failure: true

test:
    stage: build
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f .ci/Dockerfile -t ssm-rest-python-client-test .
        - docker run ssm-rest-python-client-test pipenv run make test
        - func_rse_docker_cleanup
    tags:
        - rse-multi-builder

coverage:
    stage: build
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f .ci/Dockerfile -t ssm-rest-python-client-coverage .
        - docker run ssm-rest-python-client-coverage pipenv run make coverage
        - func_rse_docker_cleanup
    tags:
        - rse-multi-builder

test-all:
    stage: build
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f .ci/Dockerfile -t ssm-rest-python-client-test-all .
        - docker run ssm-rest-python-client-test-all pipenv run make test-all
        - func_rse_docker_cleanup
    tags:
        - rse-multi-builder
    only:
        - dev
        - master
        - tags

publish-package:
    stage: package
    script:
      - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker run --rm $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA bash .ci/publish-package.sh gitlab-ci-token $CI_JOB_TOKEN
    tags:
        - rse-multi-builder
    only:
        - /^v\d+\.\d+\.\d+.*$/
