stages:
    - build

include:
     remote: "https://code.ornl.gov/rse-deployment/rse-sharables/-/raw/master/.gitlab-ci-before_script.yml"

lint:
    stage: build
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f .ci/Dockerfile -t ssm-rest-python-client-lint .
        - docker run ssm-rest-python-client-lint pwd
        - docker run ssm-rest-python-client-lint ls
        - docker run ssm-rest-python-client-lint pipenv run make lint
        - func_rse_docker_cleanup
    tags:
        - rse-ssm-builder

test:
    stage: build
    script:
        - func_rse_docker_cleanup
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -f .ci/Dockerfile -t ssm-rest-python-client-test .
        - docker run ssm-rest-python-client-test pwd
        - docker run ssm-rest-python-client-test ls
        - docker run ssm-rest-python-client-test pipenv run make test
        - func_rse_docker_cleanup
    tags:
        - rse-ssm-builder
